using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.IPapercraftRenderBackend))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.IPapercraftTemplateDataAccessor))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftDocument))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftGenerator))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftInstrumentation))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftPage))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftRenderer))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftRenderOptions))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftServiceBuilder))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.PapercraftServiceCollectionExtensions))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.RasterPageInfo))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.RasterPageRenderOutput))]
[assembly: TypeForwardedTo(typeof(X39.Solutions.Papercraft.RenderFeatureUse))]
